<?php

namespace AppBundle\Repository;

/**
 * CreditInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreditInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
